# from GitHub, overriding the name and specifying a specific tag
# Forked from geerlingguy.java for open jdk
- src: https://github.com/itoc/ansible-role-java
  version: "1.7.3"
  name: java
  path: roles