---
# tasks file for hswong3i.bamboo

- name: create group
  group:
    name: "{{ bamboo_user }}"
    gid: "{{ bamboo_gid | default(None) or omit }}"
  when: bamboo_pass is string and bamboo_hash_salt is string
  notify: restart bamboo

- name: create user
  user:
    name: "{{ bamboo_user }}"
    password: "{{ bamboo_pass | password_hash('sha512', bamboo_hash_salt) }}"
    home: "{{ bamboo_home }}"
    group: "{{ bamboo_user }}"
    uid: "{{ bamboo_uid | default(None) or omit }}"
    shell: "/bin/bash"
  when: bamboo_pass is string and bamboo_hash_salt is string
  notify: restart bamboo

- name: prepare files
  file:
    dest: "{{ item.dest }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
    state: "{{ item.state }}"
  with_items:
    - { dest: "{{ bamboo_catalina }}", owner: "{{ bamboo_user }}", group: "{{ bamboo_user }}", mode: "0755", state: "directory" }
  notify: restart bamboo

- name: download package
  get_url:
    url: "{{ bamboo_url }}"
    dest: "/tmp/{{ bamboo_archive }}"
    checksum: "{{ bamboo_checksum }}"

# Change to unarchive
- name: unarchive package
  shell: |
    tar zxvf /tmp/{{ bamboo_archive }} -C {{ bamboo_catalina }} --strip-components=1
    chown -Rf {{ bamboo_user }}:{{ bamboo_user }} {{ bamboo_catalina }}
  args:
    creates: "{{ bamboo_catalina }}/bin/start-bamboo.sh"
  notify: restart bamboo

- name: copy templates
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  with_items:
    - { src: "bamboo.service.j2", dest: "/etc/systemd/system/bamboo.service",  owner: "root", group: "root", mode: "0755" }
    - { src: "setenv.sh.j2", dest: "/etc/profile.d/setenv.sh", owner: "root", group: "root", mode: "0755" }
    - { src: "server.xml.j2", dest: "{{ bamboo_catalina }}/conf/server.xml", owner: "{{ bamboo_user }}", group: "{{ bamboo_user }}", mode: "0644" }
  notify: restart bamboo


- name: copy templates
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  with_items:
    - { src: "postgresql.properties.j2", dest: "{{ bamboo_catalina }}/atlassian-bamboo/WEB-INF/classes/database-defaults/postgresql.properties", owner: "{{ bamboo_user }}", group: "{{ bamboo_user }}", mode: "0644" }
  when: bamboo_database == 'postgres'
  notify: restart bamboo

- name: enable service
  service:
    name: "bamboo"
    enabled: "yes"
  notify: restart bamboo
